### ISSUE TITLE
I am running npm start with an error, but npm run start-dev has no problem

### ISSUE THREAD

**Issue by shchf3** [chrisveness/koa-sample-web-app-api-mysql#6]
platform：windows
node version:12.2
npm 6.9

import Koa             from 'koa';            // Koa framework
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
error: Forever detected script exited with code: 1
error: Script restart attempt #3
D:\dev\koa-sample-web-app-api-mysql\app.js:12
import Koa             from 'koa';            // Koa framework

**Comment by chrisveness** [comment]
It looks as though the *esm* module is not being loaded, for some reason.

I'm afraid I don't have a Windows environment available at the moment to try to replicate.

Do you need the `forever` functionality? Try starting without `forever` by just using `node -r esm app.js` and see if that works successfully.
